### ISSUE TITLE
Question about image/perturbation resizing

### ISSUE THREAD

**Issue by linzzzzzz** [csdongxian/skip-connections-matter#1]
Thank you for the good work :) Have a quick question.

For the experiment of using RN152 as source model and IncV3 as target model. Can I ask how did you do the resizing step from 224x224 to 299x299? If you resized the 224x224 perturbation to 299x299, what algorithm did you use for upsampling?(i.e. nearest, linear, or bilinear?)

**Comment by csdongxian** [comment]
I resized images from 224x224 to 299x299 using bilinear Interpolation in the situation mentioned above.

Actually, the data loader for TensorFlow models (VGG, Inception, etc.) in my implementation is based on
https://github.com/dongyp13/Translation-Invariant-Attacks/blob/5f2433ab7ad561d78bf21dbca361e17e6b7e23aa/attack_iter.py#L88. This code uses scipy.misc.imresize, and its default interpolation is "bilinear".

Hope that answered your question :)

**Comment by linzzzzzz** [comment]
Got it. Thank you for the reply :)
