### ISSUE TITLE
ensemble attack source code?

### ISSUE THREAD

**Issue by taoye9** [csdongxian/skip-connections-matter#6]
Hi, thanks for publishing the code of this paper?

Just wonder would it be possible for you to release the ensemble attack part code?

Or maybe some reference to other people's code?

**Comment by csdongxian** [comment]
Sorry, I have deleted the original codes. Here I provide a rough idea. SGM makes gradients from some architectures much smaller than gradients from others, which results in an unbalance problem. You could normalize their gradients per model and then combine them.
