### ISSUE TITLE
Code for tensorflow version？

### ISSUE THREAD

**Issue by mesunhlf** [csdongxian/skip-connections-matter#7]
Hi, this is a insteresting work! 
I find that the repo is torch version. Can you offer me the Tensorflow code of SGM, thanks!

**Comment by mesunhlf** [comment]
I use torch code to generate adversarial examples on Resnet50 for fooling adv trained I3ens3 or IR2ens (tf. version). However, I find the performance is lower than the results in the paper. I am wondering whether I need to run TensorFlow version of SGM?

**Comment by csdongxian** [comment]
Hi, thanks for your interest in our paper.

> I find the performance is lower than the results in the paper

1. Do you select the appropriate hyper-parameter \gamma? The optimal hyper-parameter \gamma for SGM on ResNet should be gamma=0.2 (a quite low value). 
2. As an additional question, can the attack success rate of SGM be higher than that of the PGD method?

> Can you offer me the Tensorflow code of SGM

I don't have the code for the Tensorflow version. Here I can provide my own generated adversarial samples. You can download them from [Google drive](https://drive.google.com/drive/folders/16Z3MOr2EAq-HqNQUsMWWLZTVOHDJBvOO?usp=sharing) or [Baidu drive (pwd: je7x)](https://pan.baidu.com/s/16TI_l2UeOvhNCkionfelfw), and evaluate SGM performance based on them.

Hope this can be helpful :)

**Comment by mesunhlf** [comment]
您的邮件我已收到，O(∩_∩)O谢谢

**Comment by csdongxian** [comment]
If you have more questions, be free to send an email or reopen this issue.
